### PR TITLE
EP 1: German translation

### PR DESCRIPTION
**Pull request by phellmes**
This is the German translation to episode 1 I did together with Alexandra.

### CODE REVIEW

**Comment by Deevad** [comment]
Many thanks to you and Alexandra for the beautifull pull request !

Just a note, it's not necessary to clean the path of `sodipodi:absref="`  ( an old tag , when Inkscape forked the Sodipodi project back 2003 ). This path regenerate anyway at each 'Save' action and it's always absolute ( so , it's hard to fight against ). It's a sort of fallback if the real link : `xlink:href="../gfx_Pepper-and-Carrot_by-David-Revoy_E01.png"` fails. So, `xlink:href="` is the only one who matter. And your was perfectly fine! ...also , I made a script parser to check and fix them in bash mode. Thanks again!

**Comment by phellmes** [comment]
Ah, I already thought something like that about the Sodipodi reference but wasn't sure if it's used or not. Thanks for the clarification.

Another thing I experienced: If I get SVG files from Windows users and want to open them in Inkscape on Linux, the linked images aren't displayed because the path is set with backslashes instead of forward slashes. I have to correct that in code before opening - then it works. Is there a way you know to somehow prevent that?
It doesn't seem to be a problem the other way around - when giving SVG files from Linux to Windows (well, at least I got no complaints so far).

**Comment by Deevad** [comment]
New version is online: http://www.peppercarrot.com/de/article234/potion-of-flight  ! Thank you again :-)  ( hi-res during the night )

Yes, I experienced the same about the backslash / slash issue in path. I think I need to talk about it in a bug-report with Inkscape team. I'm not sure a project before Pepper&Carrot decided to use inkscape SVGs this way, with relative link and a real cross platform experience. It's certainly a rare test-case. I wouldn't be surprise if no beta-testers did test this since last 10 years.

**Comment by phellmes** [comment]
I think it's a very efficient way to use vector graphics on top of comic panels to easily swap text content and related shape layout, especially when it comes to translations. I actually proposed a similar workflow about a year ago to someone I was helping out with translations, but it didn't work out n the end. So I'm glad to see this in practical use here now on your beautiful comics. And I agree - this is a nice test for Inkscape. :-)
Next episode translations will follow soon...

**Comment by Deevad** [comment]
Thank you!

**Pull request merged**
