### PR TITLE
Korean translation

### PR DESCRIPTION
**Pull request by initbar**

### CODE REVIEW

**Comment by Deevad** [comment]
Hey @initbar ; thank you for the work and starting the Korean translation!
I'm merging it; but I'm right now in the last sprint to publish episode 17; ( ETA 30 june, the day after tomorrow ), So,  I'll take time to render and add it to the website only at the end of week.
Thanks again!

**Comment by Deevad** [comment]
Hey,

Sorry for the late, I had million things to do! :-)
- I rendered and uploaded the page, good work ! thank you.
- I added the new lang structure to the website ; [feedback here](http://www.peppercarrot.com/kr/static6/sources&page=translation)
- I understand ,[thanks to this website](http://www.metamodpro.com/browser-language-codes), you took 'kr' ISO prefix for south Korean , instead of 'ko' that can be confusing. That's ok!

You can view the online the result here:
http://www.peppercarrot.com/kr/article234/potion-of-flight

**Question:** Is the label OK ? ( I took it from Wikipedia )
2016-05-07_selection_001

**Comment by initbar** [comment]
Hello!

I'm quite honored that you give me much credit for translations :) Compared to your works, my contributions are only tip of a broomstick :laughing:

**Answer:** _한국어/조선말_, in the most extreme technicality, is valid - but the latter _조선말_ may be unnecessary as _한국어_ is more relevant to the timeline (_조선_, or [Choseon](https://en.wikipedia.org/wiki/Joseon), can be understood as the [Choseon dynasty](https://en.wikipedia.org/wiki/History_of_the_Joseon_Dynasty) rather than modern Korea). Although there are other acceptable derivatives - such as _한국말_ - I think it might be better if you use _한국어_ for the tag :)

Nonetheless, thank you for your work in **Pepper & Carrot**! I'll try to put the Korean translations up to date soon!

**Comment by Deevad** [comment]
Thank you!
I'll modify it for 한국어   :-)

(ps: I just added this overview http://www.peppercarrot.com/en/static6/sources&page=translation , to keep track of episode )

**Pull request merged**
