### PR TITLE
Added Serbian translation in folder sr.

### PR DESCRIPTION
**Pull request by mitinica**
Hi, David.

I added a Serbian translation of episode No. 1. Please check if everything is OK, so I can continue translating. 

Regards,
Milena Petrovic

### CODE REVIEW

**Comment by Deevad** [comment]
Hi Milena,
Thank you very much for submitting a new lang to Pepper&Carrot and for your contribution :+1: 
What is the best name/label for the button on top of episode?
2016-11-11_selection_003

Srpski ? or српски ?( ref: https://en.wikipedia.org/wiki/Serbian_language )

**Comment by mitinica** [comment]
Well, the translation is in Cyrillic, so "Српски" is a better option. :)

**Comment by Deevad** [comment]
Thank you! The first episode is online :)
http://www.peppercarrot.com/sr/article234/potion-of-flight

The files were easy to be rendered by render-farm and really clean.
I just saw a little 'maybe bug' ; a font-family in a panel:

2016-11-11_selection_004

**Comment by Deevad** [comment]
Fixed in https://github.com/Deevad/peppercarrot_ep01_translation/commit/c783e5140c96217724caf1f074d44054b8dddcf8  :-)

**Pull request merged**
