### PR TITLE
Updated Translation and Typesetting

### PR DESCRIPTION
**Pull request by aslanzm**
Updated and optimized the translation and typesetting. Improving typesetting and translation to prepare the comic for print. I'll do this for all the avaliable chapters. Sorry for the extra work this may cause you Deevad! Annd, a conflict right off the bat.

### CODE REVIEW

**Comment by Deevad** [comment]
Thank you for improving the translation!

**Comment by Deevad** [comment]
Hey @aslanzm ; I saw you switched the font from Midan to ZahraRoosta  ; but I can't find information about ZahraRoosta. Is it a open-source font? Let me know.

**Comment by Deevad** [comment]
( Note: reverted in PR #30 , waiting for information )

**Comment by aslanzm** [comment]
Hi there @Deevad ! This font was recently made, so I guess there won't be any information about it, anywhere on the web. A point I want to mention about Farsi fonts is that nearly none of them has copyright restrictions. The creators distribute them for free and allow everyone to use or modify them at will or even host them and let other people download them from their websites (CC0 “No Rights Reserved”). I've included the .ttf files Pepper&Carrot's font repository.

**Comment by Deevad** [comment]
Hi @aslanzm ; ok I understand, but to protect Pepper&Carrot against legal attack, I really need to work with licenses.

I just saw the Pull-request with fonts ( sorry, my bad for missing it ) https://github.com/Deevad/peppercarrot_fonts/pull/8/commits/5f226eeee0e5be15e538b16ace81dcd334b98442 ; this pull-request is a bit problematic ; because:
- It removes the font still in usage by other episodes.
- It adds fonts without license ( I know, it's frustrating when brilliant resources exist and shared as "free" without any license ). Without a clear mentioning of the author to use SIL/ GPL / Mit / CC-0 I have to assume it's free -but- proprietary. 

To move forward: Maybe you can contact the authors of the fonts and ask them to publish the font under an open license ?

**Comment by aslanzm** [comment]
@Deevad , I got it Deevad. I'll try contacting them, but if I don't get them to publish them under a license, I'll revert the fonts back to previous font choices. Sorry again for the extra work. My bad.

**Pull request merged**
